package com.xandersu.readingnotes.imooc.class404_spring_source_code.mybatis.mapper;

import com.xandersu.readingnotes.imooc.class404_spring_source_code.mybatis.model.Demo;
import com.xandersu.readingnotes.imooc.class404_spring_source_code.mybatis.model.DemoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

//@Mapper
public interface DemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    long countByExample(DemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    int deleteByExample(DemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    int insert(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    int insertSelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    List<Demo> selectByExample(DemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    Demo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Demo record, @Param("example") DemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    int updateByExample(@Param("record") Demo record, @Param("example") DemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    int updateByPrimaryKeySelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 29 17:56:12 CST 2020
     */
    int updateByPrimaryKey(Demo record);
}